from typing import Literal, NotRequired, TypedDict

OffsetPaginationQueryParams = TypedDict(
    "OffsetPaginationQueryParams",
    {
        "pageOffset": NotRequired[int | None],
        "pageSize": NotRequired[int | None],
    },
)

InvoiceMetadataQueryParams = TypedDict(
    "InvoiceMetadataQueryParams",
    {
        "sortOrder": NotRequired[str | None],
        "pageOffset": NotRequired[int | None],
        "pageSize": NotRequired[int | None],
    },
)

ListSessionsQueryParams = TypedDict(
    "ListSessionsQueryParams",
    {
        "pageSize": NotRequired[int | None],
        "sessionType": Literal["Online", "Batch"],
        "referenceNumber": NotRequired[str | None],
        "dateCreatedFrom": NotRequired[str | None],
        "dateCreatedTo": NotRequired[str | None],
        "dateClosedFrom": NotRequired[str | None],
        "dateClosedTo": NotRequired[str | None],
        "dateModifiedFrom": NotRequired[str | None],
        "dateModifiedTo": NotRequired[str | None],
        "statuses": NotRequired[
            list[Literal["InProgress", "Succeeded", "Failed", "Cancelled"]] | None
        ],
    },
)

ListTokensQueryParams = TypedDict(
    "ListTokensQueryParams",
    {
        "status": NotRequired[list[str] | None],
        "description": NotRequired[str | None],
        "authorIdentifier": NotRequired[str | None],
        "authorIdentifierType": NotRequired[str | None],
        "pageSize": NotRequired[int | None],
    },
)

type CurrencyCodes = Literal[
    "AED",
    "AFN",
    "ALL",
    "AMD",
    "ANG",
    "AOA",
    "ARS",
    "AUD",
    "AWG",
    "AZN",
    "BAM",
    "BBD",
    "BDT",
    "BGN",
    "BHD",
    "BIF",
    "BMD",
    "BND",
    "BOB",
    "BOV",
    "BRL",
    "BSD",
    "BTN",
    "BWP",
    "BYN",
    "BZD",
    "CAD",
    "CDF",
    "CHE",
    "CHF",
    "CHW",
    "CLF",
    "CLP",
    "CNY",
    "COP",
    "COU",
    "CRC",
    "CUC",
    "CUP",
    "CVE",
    "CZK",
    "DJF",
    "DKK",
    "DOP",
    "DZD",
    "EGP",
    "ERN",
    "ETB",
    "EUR",
    "FJD",
    "FKP",
    "GBP",
    "GEL",
    "GGP",
    "GHS",
    "GIP",
    "GMD",
    "GNF",
    "GTQ",
    "GYD",
    "HKD",
    "HNL",
    "HRK",
    "HTG",
    "HUF",
    "IDR",
    "ILS",
    "IMP",
    "INR",
    "IQD",
    "IRR",
    "ISK",
    "JEP",
    "JMD",
    "JOD",
    "JPY",
    "KES",
    "KGS",
    "KHR",
    "KMF",
    "KPW",
    "KRW",
    "KWD",
    "KYD",
    "KZT",
    "LAK",
    "LBP",
    "LKR",
    "LRD",
    "LSL",
    "LYD",
    "MAD",
    "MDL",
    "MGA",
    "MKD",
    "MMK",
    "MNT",
    "MOP",
    "MRU",
    "MUR",
    "MVR",
    "MWK",
    "MXN",
    "MXV",
    "MYR",
    "MZN",
    "NAD",
    "NGN",
    "NIO",
    "NOK",
    "NPR",
    "NZD",
    "OMR",
    "PAB",
    "PEN",
    "PGK",
    "PHP",
    "PKR",
    "PLN",
    "PYG",
    "QAR",
    "RON",
    "RSD",
    "RUB",
    "RWF",
    "SAR",
    "SBD",
    "SCR",
    "SDG",
    "SEK",
    "SGD",
    "SHP",
    "SLL",
    "SOS",
    "SRD",
    "SSP",
    "STN",
    "SVC",
    "SYP",
    "SZL",
    "THB",
    "TJS",
    "TMT",
    "TND",
    "TOP",
    "TRY",
    "TTD",
    "TWD",
    "TZS",
    "UAH",
    "UGX",
    "USD",
    "USN",
    "UYI",
    "UYU",
    "UYW",
    "UZS",
    "VES",
    "VND",
    "VUV",
    "WST",
    "XAF",
    "XAG",
    "XAU",
    "XBA",
    "XBB",
    "XBC",
    "XBD",
    "XCD",
    "XCG",
    "XDR",
    "XOF",
    "XPD",
    "XPF",
    "XPT",
    "XSU",
    "XUA",
    "XXX",
    "YER",
    "ZAR",
    "ZMW",
    "ZWL",
]

KsefInvoiceTypes = Literal[
    "vat",  # Podstawowa (FA)
    "zal",  # Zaliczkowa (FA)
    "kor",  # Korygująca (FA)
    "roz",  # Rozliczeniowa (FA)
    "upr",  # Uproszczona (FA)
    "kor_zal",  # Korygująca fakturę zaliczkową (FA)
    "kor_roz",  # Korygująca fakturę rozliczeniową (FA)
    "vat_pef",  # Podstawowa (PEF)
    "vat_pef_sp",  # Specjalizowana (PEF)
    "kor_pef",  # Korygująca (PEF)
    "vat_rr",  # Podstawowa (RR)
    "kor_vat_rr",  # Korygująca (RR)
]
