# Generated by scripts/gen_sync.py from src/ksef2/clients/async_peppol.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

from collections.abc import Iterator
from typing import final

from ksef2.core.protocols import Middleware
from ksef2.domain.models.pagination import OffsetPaginationParams
from ksef2.domain.models.peppol import ListPeppolProvidersResponse, PeppolProvider
from ksef2.endpoints.peppol import PeppolEndpoints
from ksef2.infra.mappers.peppol import from_spec


@final
class PeppolClient:
    """Service for querying Peppol service providers.

    Catch ``KSeFException`` for SDK-classified failures raised by this branch,
    and ``httpx.HTTPError`` for transport failures.

    Raises:
        KSeFApiError: If KSeF returns an API error response. Catch
            ``KSeFAuthError`` for authentication or authorization failures and
            ``KSeFRateLimitError`` for throttling.
        KSeFValidationError: If a KSeF response cannot be parsed into SDK models.
        httpx.HTTPError: If the HTTP transport fails before KSeF returns a response.
    """

    def __init__(self, transport: Middleware):
        self._transport = transport
        self._endpoints = PeppolEndpoints(transport)

    def query(
        self,
        *,
        params: OffsetPaginationParams | None = None,
    ) -> ListPeppolProvidersResponse:
        """Query Peppol service providers.

        Args:
            params: Pagination parameters.

        Returns:
            QueryPeppolProvidersResponse containing the list of providers
            and pagination info.
        """
        current_params = params or OffsetPaginationParams()
        response = self._endpoints.query_providers(**current_params.to_query_params())
        return from_spec(response)

    def all(
        self, *, params: OffsetPaginationParams | None = None
    ) -> Iterator[PeppolProvider]:
        """Iterate over all Peppol service providers.

        This method handles pagination internally.

        Args:
            params: Pagination parameters.

        Returns:
            Iterator over PeppolProvider objects.
        """
        current_params = params or OffsetPaginationParams()

        while True:
            response = self.query(params=current_params)
            for provider in response.providers:
                yield provider

            if not response.has_more:
                break

            current_params = current_params.next_page()
