# Generated by scripts/gen_sync.py from src/ksef2/endpoints/async_base.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

"""Shared parsing and query-parameter helpers for endpoint wrappers."""

import abc
from collections.abc import Mapping
from typing import ClassVar

import httpx
from pydantic import BaseModel

from ksef2.core.protocols import Middleware
from ksef2.endpoints.shared import (
    DEFAULT_PARAMS_ADAPTER,
    QueryParamsAdapter,
    parse_response,
    parse_response_list,
)
from ksef2.endpoints.shared import (
    build_params as build_query_params,
)


class BaseEndpoints(abc.ABC):
    """Base class for endpoint wrappers around the transport middleware chain."""

    _PARAMS_ADAPTER: ClassVar[QueryParamsAdapter] = DEFAULT_PARAMS_ADAPTER

    def __init__(self, transport: Middleware):
        """Bind the endpoint wrapper to a transport implementation."""
        self._transport = transport

    @classmethod
    def _parse[T: BaseModel](
        cls, response: httpx.Response, response_type: type[T]
    ) -> T:
        """Parse a JSON response body into one generated schema model."""
        return parse_response(response, response_type)

    @classmethod
    def _parse_list[T: BaseModel](
        cls, response: httpx.Response, response_type: type[T]
    ) -> list[T]:
        """Parse a JSON response body into a list of generated schema models."""
        return parse_response_list(response, response_type)

    def build_params(
        self,
        params: Mapping[str, object],
        adapter: QueryParamsAdapter | None = None,
    ) -> httpx.QueryParams:
        """Validate, drop ``None`` values, and encode query parameters."""
        return build_query_params(params, adapter or self._PARAMS_ADAPTER)
